### PR TITLE
Remove errant backticks in CentOS-7/cms/wordpress-nginx.yml

### PR DESCRIPTION
**Pull request by andrewsomething**
Fix for #25 

CC: @ryanpq

### CODE REVIEW

**Comment by mesiapk** [comment]
This fixes the passwords being displayed, but there is still "tr: Broken Pipe" and "tr: Write Error" along with WordPress not having the proper permissions to write to its directory.

If you were to try and delete a plugin, or upgrade WordPress (through the site) it would ask for FTP information, since it can't write. There is no option for SFTP.

**Comment by mesiapk** [comment]
Doesn't fix the issue of the WordPress directory not having the proper ownership/write permissions.

Should line 94:
    - chown -Rf nginx.nginx /var/www/html/*
Look like this
   - chown -Rf nginx:nginx /var/www/html/*

**Comment by andrewsomething** [comment]
Using a dot (".") rather than a colon (":") is [actually valid](http://www.gnu.org/software/coreutils/manual/html_node/chown-invocation.html):

```
asb@asb-do:~$ touch foo
asb@asb-do:~$ ls -la foo
-rw-rw-r-- 1 asb asb 0 Dec  1 10:01 foo
asb@asb-do:~$ sudo chown root.root foo
asb@asb-do:~$ ls -la foo
-rw-rw-r-- 1 root root 0 Dec  1 10:01 foo
```

I think the issue with installing plugins is different. It think `define( 'FS_METHOD', 'direct' );`

@ryanpq can you take a look at this?

**Comment by ryanpq** [comment]
:+1:  Looking into it.

**Comment by mesiapk** [comment]
@ryanpq do you think it would be better to create a "wp-user" and add them to the nginx group?

**Comment by mesiapk** [comment]
@ryanpq any luck with looking into the ftp socket method?

**Pull request merged**
